blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/subspace/blockscout-frontend/issues
    about: Request a feature or enhancement
  - name: Ask a question
    url: https://forum.subspace.network
    about: Ask questions and discuss topics with other community members
  - name: Join our Discord Server
    url: https://discord.com/invite/subspace-network
    about: The official Subspace Network Discord community
